dist:
  name: otelcol-dynatrace
  description: Custom OpenTelemetry Collector distribution
  output_path: ./dist
  version: ${VERSION}

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.137.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.137.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.137.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.137.0
  - gomod: github.com/solarekm/observability/Dynatrace-opentelemetry-collector-contrib/receiver/dynatracereceiver v0.0.0-20251016151306-e17d12273c2d

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.137.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0