dist:
  name: otelcol-dynatrace
  description: Custom OpenTelemetry Collector with minimal components
  output_path: ./dist
  version: ${VERSION}
  otelcol_version: 0.137.0

exporters:
  # Core exporters only
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.137.0
  
  # Contrib exporters
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.137.0

processors:
  # Core processors only
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.137.0
  - gomod: go.opentelemetry.io/collector/processor/resourceprocessor v0.137.0

receivers:
  # Core receivers only
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.137.0
  
  # Contrib receivers  
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.137.0

extensions:
  # Contrib extensions
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.137.0