# OpenTelemetry Collector Configuration
# Environment variables required:
# - DEPLOYMENT_ENVIRONMENT
# - CLUSTER_NAME

receivers:
  # OTLP Receiver for data collection
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Host metrics receiver
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:

processors:
  # Batch processor for optimization
  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Resource processor - add metadata
  resource:
    attributes:
      - key: environment
        value: ${env:DEPLOYMENT_ENVIRONMENT}
        action: upsert
      - key: collector.version
        value: "1.0.0"
        action: upsert
      - key: cluster.name
        value: ${env:CLUSTER_NAME}
        action: upsert

  # Transform processor - data transformations
  transform:
    metric_statements:
      - context: metric
        statements:
          # Normalize metric names
          - set(name, "otelcol." + name) where name != nil
          # Add labels
          - set(attributes["source"], "hostmetrics")

exporters:
  # Logging exporter for debugging
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # Prometheus exporter
  prometheus:
    endpoint: "0.0.0.0:8888"
    namespace: "otelcol"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/health"

service:
  extensions: [health_check]
  
  pipelines:
    # Main pipeline for metrics
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [resource, transform, batch]
      exporters: [logging, prometheus]

  telemetry:
    logs:
      level: "info"
      development: false
    
    metrics:
      level: "detailed"
      address: "0.0.0.0:8888"
    
    resource:
      service.name: "otelcol-dynatrace"
      service.version: "1.0.0"