# OpenTelemetry Collector Configuration - Minimal Setup

receivers:
  # OTLP Receiver
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Dynatrace Receiver
  dynatracereceiver:
    endpoint: "https://your-dynatrace-tenant.live.dynatrace.com"
    api_token: "your-api-token"
    collect_interval: 60s
    metrics:
      - name: "host.cpu.usage"
        dimensions: ["host.name"]
      - name: "host.memory.usage"  
        dimensions: ["host.name"]

processors:
  # Filter processor
  filter:
    metrics:
      include:
        match_type: strict
        metric_names: []

  # Transform processor
  transform:
    metric_statements:
      - context: metric
        statements:
          - set(name, "transformed." + name) where name != nil

connectors:
  # Routing connector
  routing:
    default_pipelines: [metrics/default]
    table:
      - statement: route() where IsMatch(name, ".*")
        pipelines: [metrics/default]

exporters:
  # Debug exporter
  debug:
    verbosity: basic

  # OTLP HTTP exporter
  otlphttp:
    endpoint: http://localhost:4318

service:
  pipelines:
    # Default metrics pipeline
    metrics/default:
      receivers: [otlp, dynatracereceiver]
      processors: [filter, transform]
      exporters: [debug, otlphttp]

  telemetry:
    logs:
      level: "info"
