name: Build and Deploy OT Collector Contrib - Single Job

# Manual workflow for building OpenTelemetry Collector with Dynatrace receiver
# Single job approach - all operations in one job with shared filesystem
run-name: Build and Deploy OT Collector - Single Job [${{ github.event.inputs.environment }}] - JFrog:${{ github.event.inputs.deploy_to_jfrog }} Docker:${{ github.event.inputs.build_and_push_docker }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: choice
        options:
          - DEV
          - TST
        default: DEV
      deploy_to_jfrog:
        description: 'Deploy binary to JFrog Artifactory'
        required: false
        default: false
        type: boolean
      build_and_push_docker:
        description: 'Build and push Docker image to AWS ECR'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  id-token: write

env:
  GOLANG_VERSION: '1.24'
  OCB_VERSION: '0.137.0'

jobs:
  # JFrog deployment - uses repository secrets (shared across environments)
  jfrog-deploy:
    name: Deploy to JFrog Artifactory
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy_to_jfrog == 'true'
    needs: build-and-deploy-all
    
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-and-deploy-all.outputs.binary-artifact-name }}

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: 2.81.0
        env:
          JF_URL: ${{ secrets.JFROG_URL }}
          JF_USER: ${{ secrets.JFROG_USERNAME }}
          JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

      - name: Upload to JFrog Artifactory
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          VERSION=${{ needs.build-and-deploy-all.outputs.version }}
          FILENAME=${{ needs.build-and-deploy-all.outputs.binary-filename }}
          
          jf rt upload "$FILENAME" \
            "${{ secrets.JFROG_REPOSITORY }}/otelcol-dynatrace/$ENVIRONMENT/$VERSION/linux-amd64/" \
            --build-name="otelcol-dynatrace-$ENVIRONMENT" \
            --build-number="$VERSION" \
            --module="otelcol-dynatrace-$ENVIRONMENT-linux-amd64"
          jf rt build-publish "otelcol-dynatrace-$ENVIRONMENT" "$VERSION"

  # Main build and AWS deployment - uses environment secrets (DEV/TST specific)
  build-and-deploy-all:
    name: Build and Deploy Binary and Docker Image (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      environment: ${{ steps.version.outputs.environment }}
      binary-filename: ${{ steps.version.outputs.binary-filename }}
      binary-artifact-name: ${{ steps.version.outputs.binary-artifact-name }}
      docker-tag: ${{ steps.version.outputs.docker-tag }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}
          cache: false

      - name: Generate version and filenames
        id: version
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # For tags, use clean version without env prefix
            VERSION_CLEAN=${GITHUB_REF#refs/tags/v}
            VERSION_FULL="v${VERSION_CLEAN}"
          else
            # For development builds, create clean version identifier
            VERSION_CLEAN="$(echo $GITHUB_SHA | cut -c1-8)-${TIMESTAMP}"
            VERSION_FULL="dev-${VERSION_CLEAN}"
          fi
          ENV=${{ github.event.inputs.environment }}
          OS="linux"
          ARCH="amd64"
          
          echo "version=$VERSION_FULL" >> $GITHUB_OUTPUT
          echo "environment=$ENV" >> $GITHUB_OUTPUT
          echo "binary-filename=otelcol-dynatrace-${ENV}-${VERSION_CLEAN}-${OS}-${ARCH}.tar.gz" >> $GITHUB_OUTPUT
          echo "binary-artifact-name=otelcol-dynatrace-${ENV}-${VERSION_CLEAN}-${OS}-${ARCH}" >> $GITHUB_OUTPUT
          echo "docker-tag=otelcol-dynatrace-${ENV}-${VERSION_CLEAN}-${OS}-${ARCH}" >> $GITHUB_OUTPUT

      - name: Install OpenTelemetry Collector Builder
        run: |
          curl --proto '=https' --tlsv1.2 -fL -o ocb \
            "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv${{ env.OCB_VERSION }}/ocb_${{ env.OCB_VERSION }}_linux_amd64"
          chmod +x ocb
          ./ocb version

      - name: Build OpenTelemetry Collector
        run: |
          export VERSION="${{ steps.version.outputs.version }}"
          export GOOS=linux
          export GOARCH=amd64
          ./ocb --config builder-config.yaml
      
      - name: Create binary archive
        run: |
          cd dist
          chmod +x otelcol-dynatrace
          tar -czf "${{ steps.version.outputs.binary-filename }}" otelcol-dynatrace
          ls -la "${{ steps.version.outputs.binary-filename }}"
          echo "Created archive in: $(pwd)/${{ steps.version.outputs.binary-filename }}"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        if: github.event.inputs.deploy_to_jfrog == 'true'
        with:
          name: ${{ steps.version.outputs.binary-artifact-name }}
          path: dist/${{ steps.version.outputs.binary-filename }}
          retention-days: 1

      - name: Configure AWS credentials
        if: github.event.inputs.build_and_push_docker == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        if: github.event.inputs.build_and_push_docker == 'true'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare prebuilt binary for Docker build
        if: github.event.inputs.build_and_push_docker == 'true'
        run: |
          mkdir -p ./prebuilt-binary
          cp "dist/${{ steps.version.outputs.binary-filename }}" ./prebuilt-binary/
          ls -la ./prebuilt-binary/

      - name: Build and push Docker image
        if: github.event.inputs.build_and_push_docker == 'true'
        run: |
          ./scripts/docker-build.sh \
            "${{ steps.version.outputs.version }}" \
            "v${{ env.OCB_VERSION }}" \
            "${{ secrets.AWS_ECR_REGISTRY }}" \
            "${{ steps.version.outputs.docker-tag }}"

      - name: Push Docker image to ECR
        if: github.event.inputs.build_and_push_docker == 'true'
        run: |
          docker push "${{ secrets.AWS_ECR_REGISTRY }}:${{ steps.version.outputs.docker-tag }}"

      - name: Build summary
        if: always()
        run: |
          echo "Environment: ${{ steps.version.outputs.environment }}"
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Binary: ${{ steps.version.outputs.binary-filename }}"
          echo "Docker Tag: ${{ steps.version.outputs.docker-tag }}"
          if [ -f "prebuilt-binary/${{ steps.version.outputs.binary-filename }}" ]; then
            echo "Binary archive: prebuilt-binary/${{ steps.version.outputs.binary-filename }} ($(du -h "prebuilt-binary/${{ steps.version.outputs.binary-filename }}" | cut -f1))"
          fi
          if [ "${{ github.event.inputs.deploy_to_jfrog }}" == "true" ]; then
            echo "JFrog deployment: requested for ${{ steps.version.outputs.environment }}"
          fi
          if [ "${{ github.event.inputs.build_and_push_docker }}" == "true" ]; then
            echo "Docker build: requested for ${{ steps.version.outputs.environment }}"
          fi

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.binary-artifact-name }}
          path: prebuilt-binary/${{ steps.version.outputs.binary-filename }}
          retention-days: 1
